### ISSUE TITLE
Make uniform interfaces consume sampler type, rather than pixel format

### ISSUE THREAD

**Issue by bobtwinkles** [phaazon/luminance-rs#107]
While working on the code that lead to #106, I ran into an annoying papercut with the way that uniform interfaces currently work. I have source data is coming from a RGB32F buffer, which is then ping-ponged between two different R11FG11FB10F buffers to get a cheap higher-radius blur. Right now I need to compile the exact same shader program twice (and require 2 different uniform interface types) to get the types to check out. If the uniform interface/`BoundTexture` accepted something like `luminance::pixel::type::Floating` instead of a specific pixel format, that would be super helpful. It seems like it would mostly be routine plumbing (similar to the `RenderablePixel` stuff?), so I feel confident that I could do the work once a design is hashed out.

**Comment by bobtwinkles** [comment]
I've implemented a prototype for this in my fork (bobtwinkles/feature/generic_texture_uniforms). Github should have linked the commit above this comment.

**Comment by phaazon** [comment]
You can use dynamic uniform (they got added recently), but you lose the static safety. However, what you suggest is interesting and I like the idea. The `BoundBuffer` / `BoundTexture` interface is a type-safety need that has been through several iterations already (the current one on `HEAD` is a bit easier IIRC but won’t fix your current problem).

I’ll have a look at your commit! :)
