### ISSUE TITLE
luminance-derive on crates.io?

### ISSUE THREAD

**Issue by rennis250** [phaazon/luminance-rs#119]
Hey,

I really like the work you are doing here! :-)

However, it appears luminance-derive is mostly in a usable state but is not on crates.io? What holds you back?

I ask because I am not sure how to direct cargo to get a single crate from a workspace on github, and I currently resort to cloning this repository and telling cargo to look at the path on my machine.

Best and thanks,
Rob

**Comment by phaazon** [comment]
Hey!

Yeah, it’s completely stable now. There’s really nothing holding back, I’m just trying to complete [luminance-1.0](https://github.com/phaazon/luminance-rs/projects/1) before releasing all of this.

I could, however, release the current state as the next minor version, if you want to.

**Comment by phaazon** [comment]
And thak you for the kind words, I appreciate it. 🙂

**Comment by rennis250** [comment]
It's no big rush. I don't want to interrupt your plans. Thanks :)
