### ISSUE TITLE
Dynamically show/hide the mouse cursor

### ISSUE THREAD

**Issue by twetzel59** [phaazon/luminance-rs#124]
First off, I am really excited about ``luminance-rs``. It's such a clean and straightforward API!

Anyway, it would be helpful if there were a way to show or hide the mouse cursor while the program is running. I see that the ``Surface::new`` function in ``luminance-windowing`` takes a ``WindowOpt`` ``struct`` that has the option. However, it doesn't seem that the option can be changed once the ``Surface`` is created. I know that GLFW at least supports dynamic hide/show behavior. 

It's helpful for GUIs and applications that need to be able to release the cursor.

One idea is to allow changing ``Surface`` options after creation with a method like:
```rust
pub trait Surface: GraphicsContext {
    // snip
    fn set_opts(&mut self, new_opts: WindowOpt) { /* ... */ }
}
```

I suppose the viability of this design depends on the planned features in ``WindowOpt``. Right now, it just supports the mouse cursor option. Other options added in the future wouldn't necessarily be changeable at runtime...

Keep up the great work,
twetzel59

**Comment by phaazon** [comment]
Hey!

Interesting idea and in theory, completely feasible. I guess it could be done but I would do it in a slightly different way (have an `opts` functions that returns a mutable reference to the options, for instance).

The current API of the windowing system, exposed via [luminance-windowing](https://crates.io/crates/luminance-windowing), is just a way to do among others. This API is not really good to me (as you spotted, the mouse cursor stuff is linked to the window creation: re-creating a window just to hide the cursor seems completely stupid).

For sure this will be changed! Thanks for the feedback!

**Comment by phaazon** [comment]
Also, one good point is that it can be done without really interacting with the rest of `luminance` :)

**Comment by twetzel59** [comment]
No problem!

**Comment by ambihelical** [comment]
I was looking at implementing this, but since it's necessary to call self.window.set_cursor_mode when the opts have changed, I don't see how @phaazon's solution will work, but I'm pretty new to rust so I may be missing something. 

 I can see how to implement @twetzel59's solution, but there are 3 options for CursorMode, and the one most useful for hiding the mouse cursor for GUIs (at least when not full screen) is Hidden, not Disabled as the current code uses for Surface creation when hide_cursor is true.   So it doesn't seem very good either, unless the bool is changed to a 3 value enumeration mirroring the GLFW option. 

There are a number of potentially useful methods in glfw::Window so maybe it would be good to add a `fn get_glfw_window(&self) -> &Window` or similar, enabled with a glfw feature gate which would allow access to them to any applications with a special need? 

 Any advice is appreciated.

**Comment by twetzel59** [comment]
Maybe, although I get the sense that @phaazon was intending to make a backend-agnostic wrapper, i.e., GLFW could be swapped out for something else. I once forked ``luminance-glfw`` when it was its own repo because I needed this functionality, but I'd assume that it's better if the ``luminance-windowing`` crate doesn't expose the underlying window lib.

@ambihelical, as for the ``enum`` rather than the ``bool``, that sounds helpful. I have plans for a game that will need both ``Hidden`` and ``Disabled``.

Also, w.r.t. @phaazon's suggestion to return a mutable reference to ``WindowOpt``, it won't work in its current form because it needs to call a function to apply the change. However, perhaps ``WindowOpt`` could be changed to hold a reference to the window. Of course, that introduces lifetimes. So, how do we weigh that versus just an update method?

**Comment by ambihelical** [comment]
Having an "escape hatch" to expose some part of the wrapped library is a fairly common approach in rust and other languages for that matter, e.g. glfw-rs itself has apis gated on the platform (windows, linux, macos) to allow access to the platform's window and context (via glfw's own apis in this case, but this is just another example of this pattern in libraries).  This adds flexibility and puts the burden on the user of the library to use the apis correctly without coupling the library to a particular backend.  And it is not an either-or situation, if there are common window apis across backends, for example, for mouse cursor hiding, it could be added to the Surface api.

**Comment by twetzel59** [comment]
Perhaps an escape hatch is the way to go. I'm using one in my game so far.

**Comment by phaazon** [comment]
> I was looking at implementing this, but since it's necessary to call self.window.set_cursor_mode when the opts have changed, I don't see how @phaazon's solution will work, but I'm pretty new to rust so I may be missing something.

Basically, my initial idea was that we could have a function on a `Surface` that would go like `Surface::edit`, returning an object of type `SurfaceEdit` that would allow us to reset options. That object would simply mutably borrow `Surface::Self`.

Another way to do it would be to have a simple function `Surface::set_opts(_: WindowOpt)`, but this would be a _full reset_, which I feel a bit meh meh about (currently it’s only a cursor so we don’t care, but as soon as we add other things, like #91 ([initial](https://github.com/phaazon/luminance-glfw/issues/3)), such a full reset is not something I want for every occasion.
