### ISSUE TITLE
Replace the boolean for changing the cursor to a 3-value enum

### ISSUE THREAD

**Issue by phaazon** [phaazon/luminance-rs#126]
This must be changed in the `WindowOpt` type and reflected in any backend. Initial discussion happening in #124.

**Comment by twetzel59** [comment]
Quick question: do all the potential backends you consider support these 3 options? If it's just GLFW, then there's no problem. But if we use, say, SDL as a backend, we should check that the same options are present.

**Comment by twetzel59** [comment]
A cursory (ha!) look at SDL hints that it supports similar options through several functions.

**Comment by phaazon** [comment]
So far, we can do it for `GLFW` only. Then, we can also put it in `luminance-windowing` and have some kind of failible mechinism for backends that would not support it.
