### ISSUE TITLE
Glutin Support

### ISSUE THREAD

**Issue by wozeparrot** [phaazon/luminance-rs#165]
This seems to be a great library, but the only thing that is currently holding me back from using it in my projects is the lack of support for glutin for windowing.

**Comment by phaazon** [comment]
Hello,

Sure thing it could be done. I remember having a try [here](https://github.com/phaazon/luminance-glutin) but didn’t finish it. I will move the code here and make it done.

**Comment by wozeparrot** [comment]
Seeing as luminance could be getting other backends, this should instead be about supporting a pure rust windowing library instead.

**Comment by phaazon** [comment]
@wozeparrot glutin is, IIRC
