### ISSUE TITLE
More control over framebuffer slots

### ISSUE THREAD

**Issue by iwikal** [phaazon/luminance-rs#173]
I'd like to be able to control wrapping, filtering etc.

**Comment by phaazon** [comment]
I’m moving this to a next milestone because it’s not that simple and `luminance-0.36` has already several items implemented ready to be shipped. I will tag it at least for `luminance-1.0` but I will try to make it shipped before.

**Comment by iwikal** [comment]
That's cool! Not the end of the world if it misses launch. On a somewhat related note, is there a way to clear the depth slot separately? I'm trying to draw a skybox, and I want to clear the depth buffer after so that the rest of the scene ends up in front.

**Comment by iwikal** [comment]
Never mind, I managed to do it by turning off depth testing when rendering the skybox, and then setting gl_Position.z to always fall on the far plane.
```glsl
  gl_Position = view_projection * vec4(position, 1.0);
  gl_Position.z = gl_Position.w;
```

**Comment by phaazon** [comment]
You mean [this](https://docs.rs/luminance/0.36.1/luminance/render_state/struct.RenderState.html#method.set_depth_test)? It is part of the `RenderState`.

**Comment by iwikal** [comment]
No, I mean this:
https://docs.rs/luminance/0.36.1/luminance/texture/enum.DepthComparison.html

**Comment by phaazon** [comment]
Oh, that should belong to the `RenderState` _too_! I’ll patch that right away!
