### ISSUE TITLE
[Question] Text rendering library?

### ISSUE THREAD

**Issue by JoeHowarth** [phaazon/luminance-rs#188]
Hi!

Just poking around this library and it seems really interesting! Before getting too involved, I was wondering if there is a text rendering library available to use with this, as I really dislike the look of simple glyphs, but don't want to reimplement a full text renderer for a different api/platform.

Thanks!
Joe

**Comment by phaazon** [comment]
Hello!

Currently, no, no text renderer exists for luminance. Some crates exist for OpenGL but you have to mix them and it’s not really hygienic (or do an offline glyph renderer).

**Comment by JohnDoneth** [comment]
I have recently developed and published a first iteration of [luminance-glyph](https://github.com/JohnDoneth/luminance-glyph) which should allow for easy integration with existing luminance based projects.

**Comment by phaazon** [comment]
Closing in favor of `luminance-glyph`.
