### ISSUE TITLE
Cubemap wants too many pixels

### ISSUE THREAD

**Issue by iwikal** [phaazon/luminance-rs#226]
```rust
let pixels = [0; 256 * 256];
texture.upload_part_raw(
    GenMipmaps::Yes,
    ([0, 0], CubeFace::PositiveX),
    256,
    &pixels,
).unwrap();
```

Trying to upload an image to one of the faces on a cubemap, it fails with `NotEnoughPixels(50331648, 65536)`.
50331648 is 256 * 256 * 256 * 3, so it seems like it expects a three dimensional texture.

**Comment by phaazon** [comment]
Thanks for both the bug report and the fix! :muscle:
