### ISSUE TITLE
Support for sRGB textures and framebuffers.

### ISSUE THREAD

**Issue by johann2** [phaazon/luminance-rs#241]
Is support for sRGB texture formats planned? I'd be happy to implement it myself, but I might need some pointers on how the API should look like.

**Comment by phaazon** [comment]
Hello,

They’re not _planned_ but I’d be happy to integrate them. Currently, the texture API looks like this:

- A [`Texture<L, D, P>`](https://docs.rs/luminance/0.37.1/luminance/texture/struct.Texture.html) has type variables representing its flavour. `L` must be [`Layerable`](https://docs.rs/luminance/0.37.1/luminance/texture/trait.Layerable.html), `D` must be [`Dimensionable`](https://docs.rs/luminance/0.37.1/luminance/texture/trait.Dimensionable.html) and `P` must be a [`Pixel`](https://docs.rs/luminance/0.37.1/luminance/pixel/trait.Pixel.html).
- `Dimensionable` and `Layerable` already have their implementors for most common cases. It’s very unlikely you will have to any any others.
- The `Pixel` type represents what the texture pixel format is, but this is decorrelated  from how we can _sample_ from it with a [`Sampler`](https://docs.rs/luminance/0.37.1/luminance/texture/struct.Sampler.html). What it means is that you can have a given format for a texture but sample with a different, compatible format. For instance, if you use [`NormRGBA8UI`](https://docs.rs/luminance/0.37.1/luminance/pixel/struct.NormRGBA8UI.html) for texture format, each pixel is going to be stored as a 4-channel (RGBA) 8-bit unsigned integers (that is, `0-255`). **But**, when you will sample from it, you will get 32-bit floating point numbers in `0.0-1.0` — the `Norm` in the type gives that information.
- The way we associate a sampling type to a pixel type is done via a type-family (associated type in [`Pixel`](https://docs.rs/luminance/0.37.1/luminance/pixel/trait.Pixel.html), [`SamplerType`](https://docs.rs/luminance/0.37.1/luminance/pixel/trait.Pixel.html#associatedtype.SamplerType).
- `SamplerType` must be implemented for a custom type to explain how sampling should be done.

So in your case, I guess all you need to do is to create a specific kind of sampler type, like `SRGB*`, and SRGB versions of pixel type you want. The big question is: does it make sense to have SRGB + normalized? If so, I guess it means to create a combination of types, which might not be very pleasant to work with, but I don’t really know so far.

**Comment by johann2** [comment]
Hello,

Thanks for the explanation. I've managed to put something together, but I can't test it before the next week. Let me know if the interface is OK at least.
https://github.com/johann2/luminance-rs

**Comment by phaazon** [comment]
I’ll have a look at it! Thank you **so much**!

**Comment by phaazon** [comment]
The interface looks okay to me!
