### ISSUE TITLE
f64 support in Uniform

### ISSUE THREAD

**Issue by PvdBerg1998** [phaazon/luminance-rs#245]
I require higher precision, but currently I can't pass `f64`'s via `Uniform` because they do not implement `Uniformable`. Is there a specific reason why this is not implemented? Perhaps there is a workaround?

**Comment by phaazon** [comment]
There’s no current workaround but it’s very easy to implement. Why there’s none is linked to the fact the code I wrote to support uniforms (i.e. which types) has been there since the beginning, and at the beginning, I just didn’t need double precision.

I guess we can add them! :)

**Comment by iwikal** [comment]
It looks to me like there isn't any support for f64 uniforms in OpenGL. There's no mention of doubles on this page: https://www.khronos.org/opengl/wiki/GLAPI/glUniform
@PvdBerg1998 Maybe you can make better use of the available 32 bits by scaling your floats to a different range?

**Comment by phaazon** [comment]
GLSL supports `double` but the OpenGL API doesn’t for uniforms, yeah. There’s [this](https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_gpu_shader_fp64.txt) but I’m not a huge fan of adding that to luminance with the current design. It might be possible after I have merged all the reworking I’m doing.

**Comment by PvdBerg1998** [comment]
I can't (I was rendering fractals) but this doesn't have high priority at all

**Comment by PvdBerg1998** [comment]
> GLSL supports `double` but the OpenGL API doesn’t for uniforms, yeah. There’s [this](https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_gpu_shader_fp64.txt) but I’m not a huge fan of adding that to luminance with the current design. It might be possible after I have merged all the reworking I’m doing.

I just saw the update on reddit, great work! Does this statement still hold?

**Comment by phaazon** [comment]
Thanks. Well, I think it’s possible to either provide them by using the extension, feature-gated in `luminance-gl`, or add the extension as a requirement to compile `luminance-gl` if it’s supported widely enough.

**Comment by phaazon** [comment]
So, I’m tackling this right now. I am going to add support for it, but the hardware coverage [is very low](https://feedback.wildfiregames.com/report/opengl).

![img_072520_165031](https://user-images.githubusercontent.com/506592/88459629-0ce5ed00-ce97-11ea-8afe-42dfb81d5002.png)

It will be feature-gated, and disabled by default.
