### ISSUE TITLE
GLFW wait_event results in "not responding" on Win10

### ISSUE THREAD

**Issue by PvdBerg1998** [phaazon/luminance-rs#246]
See title. I don't need to render at full speed, since I'm rendering something static. I thought I'd change the `poll_event` to `wait_event` so it will block my render loop. However, this results in Win10 thinking the application is not responding. I'm not sure if this is the expected behaviour.

**Comment by phaazon** [comment]
Hm, I think you need to read messages on Windows or something. I don’t really recall _exactly_. Let me inquire a bit. Thanks for reporting!

**Comment by phaazon** [comment]
Do you still have that error? I am not able to reproduce right now.

**Comment by phaazon** [comment]
Closing for stale issue.
