### ISSUE TITLE
glfw::Modifiers not exported?

### ISSUE THREAD

**Issue by ambihelical** [phaazon/luminance-rs#247]
I am having compile-time trouble using luminance_glfw::Modifiers to capture a control key held down with another key. I'm still plenty new to rust, but I see in luminance-glfw/src/lib.rs, there is this statement:

`pub use glfw::{Action, InitError, Key, MouseButton, WindowEvent};`

Shouldn't Modifiers be in that list?

My project's luminance dependencies:
```
luminance = { version = "0.37"}
luminance-derive = { version = "0.5"}
luminance-glfw = { version = "0.11"}
luminance-windowing = { version = "0.8"}

```

**Comment by phaazon** [comment]
Yeah, I think it should. I wonder what’s the best to do here. Two possibilities:

1. We re-export everything from `glfw`.
2. We let users depend and use `glfw` directly.

**Comment by phaazon** [comment]
This issue should be completely out of date now that the model of windowing has changed. I’m closing the issue because of this, but feel free to re-open if you still have issues.
