### ISSUE TITLE
Set cursor position

### ISSUE THREAD

**Issue by BrandonDyer64** [phaazon/luminance-rs#253]
Is there any way in luminance-rs to set the position of the mouse cursor?

I've been looking high and low for some way to do this.

**Comment by phaazon** [comment]
Hello,

This is not in the scope of `luminance`, but the windowing crate you use (`glfw`, `glutin`, `glm`, etc.). Currently, the luminance backend crates for windowing (i.e. `luminance-glutin`) re-export the underlying crate but I might change that as it’s confusing people.

You should find what you look for in `glutin` in the case above or whatever crate you’re using. :)

**Comment by phaazon** [comment]
Closing for stall and out of scope.
