### ISSUE TITLE
X Error caused by GlfwSurface.poll_events

### ISSUE THREAD

**Issue by sam-barr** [phaazon/luminance-rs#298]
The following program instantly crashes on my computer:

```rust
use luminance_glfw::{GlfwSurface, Surface as _, WindowDim, WindowOpt};

fn main() {
    let surface = GlfwSurface::new(WindowDim::Windowed(500, 500), "TEST", WindowOpt::default());

    match surface {
        Ok(mut surface) => loop {
            surface.poll_events();
            surface.swap_buffers();
        },
        Err(_) => {}
    }
}
```

The following error message is printed:
```
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  40 (X_TranslateCoords)
  Resource id in failed request:  0x0
  Serial number of failed request:  150
  Current serial number in output stream:  150
```

Using `wait_events` preduces the same result. Commenting out the `poll_events` line causes the program to run with no crashes. My window manager is xmonad 0.15, and its possible there is a bad interaction there.

**Comment by phaazon** [comment]
Which OpenGL driver are you using? Can you paste the result of the `glxinfo` command, please? :)

**Comment by sam-barr** [comment]
The result of `glxinfo` I got can be seen here: https://pastebin.com/TgaFhdKi

**Comment by phaazon** [comment]
It doesn’t seem related to `luminance`, but to `glfw`. I would like to know exactly what fails but I don’t really know how to debug `glfw`… I guess we need a `glfw` developer. I’ll ask for help. Thanks! :)

**Comment by sam-barr** [comment]
glfw-sys upgraded to version 3.3.2, and this appears to have fixed this issue
