### ISSUE TITLE
Add ability to decouple texture from framebuffer

### ISSUE THREAD

**Issue by negamartin** [phaazon/luminance-rs#300]
Currently textures can only be borrowed from framebuffers, so the underlying framebuffer has to be kept alive while it is in use.

**Comment by phaazon** [comment]
I don’t get your question. You can use textures if you want to without having to use a framebuffer.

**Comment by phaazon** [comment]
Or… maybe I think I get what you mean. You want to be able to get rid of a framebuffer to just get back the textures, like one shot framebuffers? That is currently not possible indeed, but, yeah, it’s _very easy_ to implement! I’ll consider it!

**Comment by negamartin** [comment]
Exactly, one shot framebuffers is the description of what I'm looking for.

Thanks for looking into it!
