### ISSUE TITLE
What's the purpose of having backend-specific TessBuilders?

### ISSUE THREAD

**Issue by iwikal** [phaazon/luminance-rs#318]
In the process of opening a pull request with my Sdl2Surface, I learned of this rewrite you're doing, and thought I'd rebase on that first. Then, to test that it still works after the rewrite, I had to port my game project to luminance 0.40 too, and I came upon some friction with the TessBuilders. Now, every call to a builder method is apparently fallible, so I had to unwrap at every step of the process.

#### Before:
```rust
    TessBuilder::new(context)
        .set_mode(Mode::TriangleStrip)
        .set_primitive_restart_index(Some(restart))
        .set_vertex_nb(indices.len())
        .set_indices(indices)
        .build()
        .unwrap()
```
#### After:
```rust
    TessBuilder::new(context)
        .unwrap()
        .set_mode(Mode::TriangleStrip)
        .unwrap()
        .set_primitive_restart_index(Some(restart))
        .unwrap()
        .set_vertex_nb(indices.len())
        .unwrap()
        .set_indices(indices)
        .unwrap()
        .build()
        .unwrap()
```

I could perhaps make use of the question mark operator to make it more concise
```rust
    (|| {
        TessBuilder::new(context)?
            .set_mode(Mode::TriangleStrip)?
            .set_primitive_restart_index(Some(restart))?
            .set_vertex_nb(indices.len())?
            .set_indices(indices)?
            .build()
    })()
    .unwrap()
```

But it doesn't really feel like a Builder pattern anymore. It would feel a lot more builder-y if, like before, the builder is a "dumb" collection of settings that don't do anything, and only materialize once you call ".build()", which suggests that the builder should not be concerned with backend stuff untill it's time to complete the build. Just my two cents.

**Comment by iwikal** [comment]
If I had bothered to look at the examples, I would have seen your intended usage which is much nicer:
```rust
TessBuilder::new(context)
    .and_then(|b| b.set_mode(Mode::TriangleStrip))
    .and_then(|b| b.set_primitive_restart_index(Some(restart)))
    .and_then(|b| b.set_vertex_nb(indices.len()))
    .and_then(|b| b.set_indices(indices))
    .build()
    .unwrap()
```

I also realized that the reason it has to upload vertices and stuff eagerly is so that it doesn't have to hold on to them, either in borrowed form or copy them to an owned `Vec`, until it's time to build. The things we do for performance, I guess.

**Comment by phaazon** [comment]
Yep, I like that pattern. :hand_over_mouth: 

Talking about local buffering, I’m currently doing that in the WebGL backend — because heck, WebGL doesn’t have buffer mapping.

About the interface, it does borrow, via `AsRef<[V]>`. The idea is that you don’t need to move / copy anything, as the backend will do the copy itself — by using an immutable pointer. _However_, as mentioned above, that is backend-dependent. For instance, in WebGL, it’s very likely that I will clone the buffer to keep a copy around and emulate persistent mapping — which is what I’m currently doing on my branch.

Yeah. That kind of operations is tedious. :D
