### ISSUE TITLE
Selectively resetting cached graphics state

### ISSUE THREAD

**Issue by SpacialCircumstances** [phaazon/luminance-rs#333]
Hello,

I have a question/suggestion related to the GraphicsState stored by luminance-gl.
I'm currently trying to integrate luminance together with other libraries that do OpenGL calls (to be exact: WebRender and pathfinder).
This causes several problems, because luminance caches the graphics state e.g. bound shader programs in the GraphicsState struct.
Other libraries will then change this state, and luminance will attempt to render without a shader program, or without a VBO, which of course fails.
Now, my question is: Is there a elegant way of selectively resetting this state? (For example, notifiying luminance that it needs to rebind the shader program).
Sadly, constructors for GraphicsState are not exposed (for good reasons, obviously).
Is there already a way of doing this?

**Comment by SpacialCircumstances** [comment]
After investigating into this for a bit, I can see no way of doing this at the moment.
But I think I have an idea how to change this: Adding public methods on the GraphicsState that allow resetting the cached values (to 0 for the shader program, for example). This would not trigger OpenGL calls directly, but instead make sure that the next time a value is used it will be set. Therefore, it could not (easily) be used to produce errors or unsafe behavior. If this feature were to be misused by a user, it would only decrease performance slightly. On the other hand, it would enable countless integrations of OpenGL-based libraries, such as NanoVG, Imgui etc.

I'm going to go ahead and try implementing this.

**Comment by phaazon** [comment]
Hello.

Sorry, I thought I had answered. About the state, I have the concept of `Bind::Forced`, to force something to by-pass caching. However, this is an internal feature.

Maybe the feature you want is just a way to disable the internal state tracker. That should be a feature of the backend — `luminance-gl`, for instance.

**Comment by phaazon** [comment]
Looking at the PR, I think it’s a great addition. However, I’m not completely sure it’s the way we should do it.

The use cases, I guess is:

1. Someone makes some random GL commands.
2. They issue a `luminance` command. It must not use the cached version as the GL commands might have invalidate the GPU state.
3. Etc.

Maybe what is needed is simply a way to say “from now on, do not cache” and “now, cache again.” I’m still not quite sure exactly about the scope of such a feature.

**Comment by SpacialCircumstances** [comment]
Exactly, those are the use cases for such a feature.

The advantage over a feature flag I can see is avoiding unnecessary changes. For example, [NanoVG](https://github.com/memononen/nanovg) documents the GL state touched by it. Fully disabling caching would decrease performance in this case. Also, imagine something like a debug UI (using imgui or something similar) that can be enabled at runtime. It would be bad to fully disable caching in that case. So, I don't think a feature flag would be the way to go. 

But there are probably other, possibly better ways of realizing this feature that are not as error prone as my implementation (which requires careful handling by the user).

**Comment by phaazon** [comment]
Nah you are right; I’m just trying to challenge a bit the approach. I really like it. I’ll dig into the implementation a bit more tomorrow but I really like it. Congrats for the code and the idea; really nice feature! :)

**Comment by phaazon** [comment]
@SpacialCircumstances I think we can close this as the PR landed and got merged.

**Comment by SpacialCircumstances** [comment]
Of course, sorry! I totally forgot that the issue was still open.

**Comment by phaazon** [comment]
No problem, I was just wanting to be sure your issue was fully addressed. Thanks again. :)
