### ISSUE TITLE
Support for custom glVertexAttribDivisors

### ISSUE THREAD

**Issue by JohnDoneth** [phaazon/luminance-rs#384]
While refactoring glow-glyph to be essentially a luminance-glyph crate to allow for font-rendering I ran into the limitation of only being able to step the vertex attributes by 0 or 1 due to this segment of the code. If we could annotate the vertex elements with custom divisors that might be a nice feature.

https://github.com/phaazon/luminance-rs/blob/0f996eb08296d52aac6f7bb4c2d3045c8bab5445/luminance-gl/src/gl33/tess.rs#L678-L682

This is the code I was attempting to refactor and am unable to replicate one-to-one in luminance.
https://github.com/hecrj/glow_glyph/blob/225089efbf80be70af525e43055077daea7a4112/src/pipeline.rs#L328-L360

**Comment by phaazon** [comment]
Hey! Thanks for your feedback. Sure we can invest some time in this feature. The next release of `luminance-0.40` is very imminent, but we can slide this feature in. I need to understand a bit more the divisor stuff, because I always struggle a bit to understand how it works exactly.

**Comment by JohnDoneth** [comment]
Ah sorry, after further debugging my problem was that I was missing `instanced = "true"` in the vertex derive proc macro and was looking at the wrong argument to `gl::VertexAttribDivisor(index, divisor)` in the code I was reading. Everything I need to do is supported as of this moment. :tada:

**Comment by JohnDoneth** [comment]
![image](https://user-images.githubusercontent.com/3239951/86965871-2d434700-c136-11ea-8500-dd61c94169ef.png)

**Comment by phaazon** [comment]
Seeeeeeeeeeeeexy!
