### ISSUE TITLE
WebGl2RenderingContext requires extensions to enable floating-point texture filtering

### ISSUE THREAD

**Issue by austinjones** [phaazon/luminance-rs#388]
Without the WebGL extensions `OES_texture_float_linear` and `EXT_color_buffer_float`, floating-point textures cannot be filtered.  They only render if the min filter and mag filter are both Nearest.

Firefox prints the message:
`WebGL warning: generateMipmap: Texture at base level is not unsized internal format or is not color-renderable or texture-filterable.`

There are also a few other extensions that are required, but are implicitly enabled: `OES_texture_float` (enabled by WebGL2) and `EXT_float_blend` (enabled by `EXT_color_buffer_float`).

**Comment by austinjones** [comment]
I'm working on a PR - it seems natural to check extensions during `WebGL2State::get_from_context`.

I'm curious about your opinion on adding these are a requirement, though.  Some mobile devices don't support them.

**Comment by phaazon** [comment]
I guess that if they’re needed, we can check for them when using floating textures, as people could still simply use integer textures on mobile, for instance. Do you have any link / documentation about all these extensions you are referring to?

**Comment by austinjones** [comment]
Ah, good idea!  I'll change the PR.

Here are some doc links: 
https://developer.mozilla.org/en-US/docs/Web/API/OES_texture_float_linear
https://developer.mozilla.org/en-US/docs/Web/API/EXT_color_buffer_float

And the implicitly enabled ones:
https://developer.mozilla.org/en-US/docs/Web/API/OES_texture_float
https://developer.mozilla.org/en-US/docs/Web/API/EXT_float_blend

And a stackoverflow that was really helpful:
https://stackoverflow.com/questions/46262432/linear-filtering-of-floating-point-textures-in-webgl2
