### ISSUE TITLE
Pointer bug with BufferSlice/BufferSliceMut in GL33 and WebGL

### ISSUE THREAD

**Issue by austinjones** [phaazon/luminance-rs#397]
There is a small typo in the BufferSlice/BufferSliceMut transmute implementations for GL33 and WebGL.

```let ptr = self.len as *const T;```

This pointer is invalid, so retrieved buffers have null entries.  Fixed by `let ptr = self.ptr as ...`

**Comment by austinjones** [comment]
I think this is the last one - everything is working!

**Comment by phaazon** [comment]
Thank you for all the nice PRs you made lately. I appreciate a lot! The release is very soon, I need to ensure everything works correctly and that fixing anything remaining won’t be a breaking change, and that should be good to ship to crates.io!

**Comment by austinjones** [comment]
No problem!  It was a great way to learn more about luminance and webgl!

And makes sense - I'm done with the torrent of bugfixes, I promise. 😉

**Comment by phaazon** [comment]
I’m glad you enjoyed the journey! :)
