### ISSUE TITLE
There doesn't seem to be a way to make a fullscreen window with luminance-glutin

### ISSUE THREAD

**Issue by iwikal** [phaazon/luminance-rs#401]
To make a fullscreen window with glutin, you need access to the event loop, but the event loop is not exposed for use in the window builder callback, so I had to resort to this trick:

```rust
    let primary_monitor = EventLoop::new().primary_monitor();

    let (mut surface, event_loop) = Surface::from_builders(
        |window_builder| {
            window_builder
                .with_fullscreen(Some(Fullscreen::Borderless(primary_monitor)))
        },
        |context_builder| context_builder,
    )?;
```

But it feels hacky to create an event loop just to throw it away immediately after and create another.

**Comment by phaazon** [comment]
Thanks, we’ll need to update that to expose it then. :)
