### ISSUE TITLE
Provide an example of Vertex definition without luminance-derive

### ISSUE THREAD

**Issue by MarekLg** [phaazon/luminance-rs#409]
It seems like it's possible to define a Vertex and its Semantics without deriving Vertex or Semantics respectively. This would be nice to see in an example, like [in chapter 2.3 of the book](https://rust-tutorials.github.io/learn-luminance/chapter_2_3.html).

**Comment by phaazon** [comment]
It is possible, but it’s `unsafe`, so such an example can be crafted but shouldn’t be in the “beginner” book to me. :)

**Comment by MarekLg** [comment]
That's understandable.. Thanks for the clarification!
