### ISSUE TITLE
Allow binding multiple HtmlCanvasElements

### ISSUE THREAD

**Issue by austinjones** [phaazon/luminance-rs#426]
Due to the `WebGL2State::new` constructor, Luminance only works with one bound canvas.
https://github.com/phaazon/luminance-rs/blob/a192fcd9ed3b15f1b69854686be81c1e6ecf0a32/luminance-webgl/src/webgl2/state.rs#L119

I didn't see any obvious statics that would prevent multiple canvases from being bound, and things seem to work fine with multiple canvases.

I'm going to play with it more, but let me know if you have any thoughts.

**Comment by phaazon** [comment]
Yes, that’s a restriction of OpenGL, but maybe that restriction is lift with WebGL.

**Comment by kpreid** [comment]
Yes, browsers support multiple independent WebGL contexts (though there is a limit on how many can exist; exceeding it causes the "context lost" state for the oldest context, at least in Chrome).

**Comment by phaazon** [comment]
Okay, I think it should be safe to just remove that TLS lock, since we have to use an explicit context. I’ll try to do that tonight. Thanks peeps for reporting!

**Comment by austinjones** [comment]
Awesome!  Thanks so much for the WebGL support.  It's been working great!

**Comment by phaazon** [comment]
I’ll release that soon with a bunch of new improvements.

**Comment by austinjones** [comment]
Wooo! 🚀
