### ISSUE TITLE
HtmlCanvasElements are always resized when mounted

### ISSUE THREAD

**Issue by austinjones** [phaazon/luminance-rs#427]
WebSysWebGL2Surface always resizes the canvas when constructed.  Perhaps the Fullscreen option should leave the canvas as is?

https://github.com/phaazon/luminance-rs/blob/2bdab0a7f3ac27f20c020d812a3f7d0818ad0086/luminance-web-sys/src/lib.rs#L102

My use case is that the canvas viewport is dynamically sized.  JS updates the canvas size dynamically, but WebSysWebGL2Surface is overwriting the dimensions with a fixed size.

**Comment by phaazon** [comment]
Yeah, I don’t really know what to do here, since users might expect `luminance-web-sys` to do the sizing.

**Comment by kpreid** [comment]
I think there are two useful behaviors here which are worth offering:

1. Automatically set the canvas size to match physical pixels (CSS computed size of the element multiplied by [devicePixelRatio](https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio)), and install a [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) to **continuously** update this size on window size/layout changes; this is highly convenient setup for full-page (whether or not fullscreen) WebGL applications. (If this is implemented, then letting the application author provide a callback for any needed re-setup/redraw on resize would be extra convenient.)
2. Don't touch the canvas size at all, for when
    * the canvas is a simple fixed size (`width`/`height` set and no CSS),
    * the application author (or framework they are using) is doing their own size management, or
    * the application author is doing something special (like "off-screen" rendering to an invisible canvas for a following `getImageData`).

In both cases, the author should not have to call `back_buffer()` again every time there is a size change (as is the status quo as I understand it).

**Comment by phaazon** [comment]
Okay so I checked the code again, and I think the saner option is to remove the resize completely. From all the discussions I had, it looks like people will want to drive that from JS directly rather than Rust, since it’s a property of the canvas directly. The `back_buffer` method even uses the canvas size to create the default framebuffer, so it makes sense. I’m removing that code.

**Comment by austinjones** [comment]
Yay!  Thank you @phaazon!
