### ISSUE TITLE
luminance_webgl: setting uniform mat4 gives runtime size error

### ISSUE THREAD

**Issue by kpreid** [phaazon/luminance-rs#434]
I'm attempting to follow along with [Learn luminance, at the point where we add a projection matrix](https://rust-tutorials.github.io/learn-luminance/chapter_3_4.html), but in WebGL (using `luminance_front` imports). If I write

```
#[derive(Debug, UniformInterface)]
struct ShaderInterface {
    #[uniform(unbound)]
    projection_matrix: Uniform<[[f32; 4]; 4]>,
}
...
                shading_gate.shade(block_program, |mut shader_iface, u, mut render_gate| {
                    let pm: [[f32; 4]; 4] = camera.matrix().cast::<f32>().unwrap().into();
                    shader_iface.set(&u.projection_matrix, pm);
```
then I get a runtime GL error

* In Chrome: `GL ERROR :GL_INVALID_OPERATION : glUniformMatrix4fv: count > 1 for non-array`
* In Firefox: `uniform setter: (uniform projection_matrix) `values` length (256) must exactle match size of <enum 0x8b5c>.`

and the display is blank. On the other hand, if I replace the `mat4` uniform with four `vec4` uniforms containing the rows of the matrix, then the matrix acts as expected in my vertex shader. This suggests that there is something wrong with luminance_webgl's implementation of calls to `glUniformMatrix4fv`, such that it is passing a too-long array, since the type system does not (as far as I can see) permit my code to contain a length error.

Let me know if you would find a specifically runnable example project handy; I'm in the middle of working around this bug but I can easily enough upload a branch that demonstrates it instead.

`cargo tree` reports the following versions in use (irrelevant items trimmed):
```
├── cgmath v0.17.0
├── js-sys v0.3.44
├── lazy_static v1.4.0
├── luminance v0.41.0
├── luminance-derive v0.6.1
│   ├── proc-macro2 v1.0.19 (*)
│   ├── quote v1.0.7 (*)
│   └── syn v1.0.38 (*)
├── luminance-front v0.2.3
│   ├── luminance v0.41.0
│   └── luminance-gl v0.14.1
│       ├── gl v0.14.0
│       │   [build-dependencies]
│       │   └── gl_generator v0.14.0
│       │       ├── khronos_api v3.1.0
│       │       ├── log v0.4.11 (*)
│       │       └── xml-rs v0.8.3
│       └── luminance v0.41.0
├── luminance-web-sys v0.1.1
│   ├── luminance v0.41.0
│   ├── luminance-webgl v0.1.1
│   │   ├── js-sys v0.3.44 (*)
│   │   ├── luminance v0.41.0
│   │   ├── serde v1.0.114
│   │   ├── serde_derive v1.0.114
│   │   │   ├── proc-macro2 v1.0.19 (*)
│   │   │   ├── quote v1.0.7 (*)
│   │   │   └── syn v1.0.38 (*)
│   │   ├── wasm-bindgen v0.2.67 (*)
│   │   └── web-sys v0.3.44
│   │       ├── js-sys v0.3.44 (*)
│   │       └── wasm-bindgen v0.2.67 (*)
│   ├── luminance-windowing v0.9.1
│   │   └── luminance v0.41.0
│   ├── wasm-bindgen v0.2.67 (*)
│   └── web-sys v0.3.44 (*)
├── luminance-webgl v0.1.1 (*)
├── luminance-windowing v0.9.1 (*)
├── wasm-bindgen v0.2.67 (*)
└── web-sys v0.3.44 (*)
```

**Comment by phaazon** [comment]
Thanks for reporting! I’m having a look.

**Comment by phaazon** [comment]
The bug comes from the implementation of the `flatten_slice!` macro: indeed, the size it uses to compute the slice is not correctly set. The syntax is:

```rust
flatten_slice!(array_or_slice_of_array, [T; N])
```

Where `N` is the size of the inner array. But in our case, we consider `N` to be the full size of all the data (we typically pass N * N for `mat4`). Because that macro can be used with slices of matrices (3-level nesting, ffs), it’s important to be able to compute the size at runtime.

I’m on it.

**Comment by phaazon** [comment]
Wait, why isn’t this closed? IIRC, I fixed this.

**Comment by kpreid** [comment]
Testing, it does not appear to be fixed in

```
luminance v0.42.2
luminance-derive v0.6.2
luminance-webgl v0.1.2
```

**Comment by phaazon** [comment]
Yeah I guess I started working on this and didn’t end it. It’s on my top-priority task for `luminance` right now. :)

![Screenshot_20201026_171149](https://user-images.githubusercontent.com/506592/97197804-5869a900-17ae-11eb-9d33-653d0c9d2e88.png)
