### ISSUE TITLE
luminance-glfw: events_rx queue does not yield any events

### ISSUE THREAD

**Issue by JohnDoneth** [phaazon/luminance-rs#435]
We're having an issue where `surface.events_rx.try_iter()` does not yield any events. Tested on Linux/11 and Linux/Wayland.

This was discovered during the upgrade of luminance-glyph to luminance 0.41: https://github.com/JohnDoneth/luminance-glyph/pull/4

**Comment by phaazon** [comment]
[The fix should be trivial for you. :)](https://github.com/phaazon/luminance-rs/blob/master/luminance-examples/src/hello-world.rs#L210-L211).

I guess it’s unlikely glfw will every call `try_iter()` without calling `poll_events` first, so I guess we could make them a PR to call it directly, but maybe there are usecases I don’t see.

**Comment by JohnDoneth** [comment]
Ah that makes sense. I had incorrectly assumed poll_events was now called under the hood somehow. Thanks!
