### ISSUE TITLE
instanced attributes ?

### ISSUE THREAD

**Issue by jice-nospam** [phaazon/luminance-rs#44]
Hey,

Can you confirm luminance does not yet support instanced attributes? I see no use of VertexAttribDivisor in the code.

**Comment by phaazon** [comment]
Yep, not used. I’ve never seen any use of those. Can you enlight me? If they’re interesting enough, they could end up in luminance!

**Comment by jice-nospam** [comment]
It's used when you use instanced rendering. You send a single render
command to draw the same model several times, using different attributes
(position/color/whatever).
So instead of feeding a single value, say, for the model_position matrix
attribute, you send an array of matrices and the GPU renders n models. Very
useful for grass, voxels, stuff like that.
http://www.informit.com/articles/article.aspx?p=2033340&seqNum=5


2017-09-15 23:31 GMT+02:00 Dimitri Sabadie <notifications@github.com>:

**Comment by phaazon** [comment]
I do that with a uniform buffers and use the `gl_InstanceID` to look up in the uniform buffer.

**Comment by jice-nospam** [comment]
mmh ok I'll give it a try this way. thanks :)

2017-09-16 2:30 GMT+02:00 Dimitri Sabadie <notifications@github.com>:

**Comment by jice-nospam** [comment]
in fact using uniform array has two drawbacks: you're limited to
GL_MAX_UNIFORM_LOCATIONS
instances (generally a few thousands) and you have to hardcode the number
of instances in the shader code.

This other tutorial explains why instanced arrays through vertex attribute
is more powerful :
https://learnopengl.com/#!Advanced-OpenGL/Instancing

Not sure how to integrate instanced attributes in luminance though. I guess
you have to use something similar to uniforms :

pub struct Program<In, Out, Uni, InstAtt>


2017-09-16 3:37 GMT+02:00 jice <jice.nospam@gmail.com>:

**Comment by phaazon** [comment]
No, not uniform arrays. Uniform buffers! I’ll have a look at that, but to me, you can cope with your need with uniform buffers.

**Comment by jice-nospam** [comment]
I had a look at uniform buffers. Apparently, they come with their own limitations. They're pretty small (64 KB on a Geforce 660). If you store 4x4 matrices, you can only have 1000 instances. This might be enough for most uses, but I'm dealing more with 10 000-100 000 instance count. It's a quite specific case though and I understand uniform buffers might be enough for most usages.

**Comment by phaazon** [comment]
Yeah, that’s right. The typical workaround for that is:

- use a TBO (not yet supported by luminance)
- use SSBO (waaaaay not supported as it’s GL41+)

I’ll have a look at that feature then!

**Comment by phaazon** [comment]
Ok, I’d like to tackle that now. I’ll try to come up with a good design for this, but I have a huuuuge refactoring of `luminance` running on (`luminance-1.0` on its way).

**Comment by jice-nospam** [comment]
Good news! :)

**Comment by phaazon** [comment]
So @jice-nospam, several months (almost a year later), the feature is there. Currently, it allows primitive vertex instancing. More complex one can be achieved by tweaking some `enum`. I’ll do that a bit later as I think the current situation covers most needs.

[Example here](https://github.com/phaazon/luminance-rs/tree/b08dc4722f9049ccfd73ae0c36096f7a2beafbf0/luminance/examples/10-vertex-instancing). If you look at the sources, you’ll see that lots of things must have been done before correctly implementing that feature (especially, I created `luminance-derive` to make the whole thing ultra simple to use to people).

Thanks again for reaching with the issue and sorry for the long delay!

**Comment by jice-nospam** [comment]
hey, thanks for sticking to this
