### ISSUE TITLE
luminance-derive generates code that doesn’t pass #![deny(missing_docs)] for Vertex / Semantics

### ISSUE THREAD

**Issue by phaazon** [phaazon/luminance-rs#446]
The solution is to, either:

- Provide a default documentation for all the generated methods (`new`, etc.).
- Mute them, but it would result with problems with `![forbid(missing_docs)]`.

**Comment by phaazon** [comment]
I can’t reproduce that bug… :confused:

**Comment by kpreid** [comment]
I just ran into this while working on more complete documentation in [my project](https://github.com/kpreid/all-is-cubes).

```
$ cargo clippy -- --warn missing_docs
...
warning: missing documentation for a struct
  --> all-is-cubes/src/lum/types.rs:18:30
   |
18 | #[derive(Copy, Clone, Debug, Semantics)]
   |                              ^^^^^^^^^
   |
   = note: this warning originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

warning: missing documentation for a struct field
  --> all-is-cubes/src/lum/types.rs:18:30
   |
18 | #[derive(Copy, Clone, Debug, Semantics)]
   |                              ^^^^^^^^^
   |
   = note: this warning originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

warning: missing documentation for an associated function
  --> all-is-cubes/src/lum/types.rs:18:30
   |
18 | #[derive(Copy, Clone, Debug, Semantics)]
   |                              ^^^^^^^^^
   |
   = note: this warning originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

warning: missing documentation for an associated function
  --> all-is-cubes/src/lum/types.rs:40:41
   |
40 | #[derive(Clone, Copy, Debug, PartialEq, Vertex)]
   |                                         ^^^^^^
   |
   = note: this warning originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
...
```

I also get such errors for my small luminance scratchpad project without using clippy if I just add `#![warn(missing_docs)]` and `cargo build`.

Let me know if a packaged-up repro would be helpful.

**Comment by phaazon** [comment]
Is it in a lib crate, @kpreid?

**Comment by kpreid** [comment]
`all_is_cubes` is a library crate but I also tested in a binary crate.

Here is a minimal project that reproduces the message: [luminance_doc_test.zip](https://github.com/phaazon/luminance-rs/files/5541409/luminance_doc_test.zip), It gives the same results whether the source file is `lib.rs` or `main.rs`.
