### ISSUE TITLE
luminance-derive fails when depending on only luminance-front

### ISSUE THREAD

**Issue by mystise** [phaazon/luminance-rs#451]
With the following cargo dependencies:

```
luminance-derive = "0.6"
luminance-front = "0.3"
```

And the following code:

```
use luminance_front::shader::Uniform;
use luminance_derive::{Semantics, UniformInterface, Vertex};

#[derive(UniformInterface)]
struct UniformInterface {
	view_projection: Uniform<[[f32; 4]; 4]>,
}

#[derive(Copy, Clone, Debug, Semantics)]
pub enum Semantics {
	#[sem(name = "position", repr = "[u16; 3]", wrapper = "Pos")]
	Position,
}

#[derive(Clone, Copy, Vertex)]
#[vertex(sem = "Semantics")]
#[repr(C)]
pub struct Vertex {
	pos: Pos,
}
```

All 3 of the luminance-derive calls fail with:

```
error[E0433]: failed to resolve: use of undeclared type or module `luminance`
   |
15 | #[derive(UniformInterface)]
   |          ^^^^^^^^^^^^^^^^ use of undeclared type or module `luminance`
   |
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

When adding ```use luminance_front as luminance;``` to the previous code, everything passes except for UniformInterface, which now errors with:

```
error[E0433]: failed to resolve: could not find `backend` in `luminance`
   |
15 | #[derive(UniformInterface)]
   |          ^^^^^^^^^^^^^^^^ could not find `backend` in `luminance`
   |
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

Adding ```luminance = "0.42"``` to the cargo dependencies and removing ```use luminance_front as luminance;``` from the code fixes the issue.

I'm unsure if depending on luminance-front but not luminance is even supposed to work, but seeing as luminance-front both depends on luminance and re-exports almost the entire thing, my first thought was to remove luminance from Cargo.toml as unnecessary.

**Comment by phaazon** [comment]
Yes, that’s a point I’ve been worrying about and it’s super hard to fix because of proc-macros, who need `luminance` and not `luminance-front`.
