### ISSUE TITLE
Should a `Tess` with zero vertices be considered erroneous?

### ISSUE THREAD

**Issue by kpreid** [phaazon/luminance-rs#452]
Currently, if you use the WebGL backend and render an empty `Tess`, i.e. `context.new_tess().set_vertices(vec![]).set_mode(Mode::Triangle).build()`, this will trigger a runtime message (in Chrome)

```
RENDER WARNING: Render count or primcount is 0.
```

From the perspective of the high-level luminance API, should a `Tess` with zero vertices be acceptable? If so, perhaps a check should be added so that if the count is zero, no draw call is made and the message is not generated. If not, perhaps the `TessBuilder` should return an error?

---

Use cases / arguments:

In my application, an empty `Tess` is useful for a case where I have either zero or one of a thing (a selection box) to render per frame — it would not save any significant compute time to make a check to skip drawing it.

Another use case would be to have a default value available for when a data structure caching a `Tess` is to be initialized before the vertices are actually computed; if that's worth supporting, then it would be additionally useful to have a way to construct an empty `Tess` without even supplying a `GraphicsContext` (which is possible since no draw calls are needed and a `Tess` cannot be enlarged to hold more vertices after construction) — thus `Tess` and types containing `Tess` can implement `Default`.

On the other hand, if `Tess` is required to be nonempty, all application code that cares about this can just work with `Option<Tess>`, and this _might_ encourage looking for opportunities to avoid doing unnecessary computation, and _might_ catch bugs where there should have been some vertices but weren't.

**Comment by phaazon** [comment]
Hello, thanks for the feedback!

I think a tess without vertices is definitely possible — i.e. attributeless tessellations, which are used quite a lot. However, in that case, passing an empty list of vertices is not the way to go: simply don’t pass any, and specify the number of vertices to render — so that the GPU pipeline knows how many vertex shader invocations do.

If we want to have “zero” vertices (with data or attributeless), then the current code allows to simply pass nothing. I guess we could add a small test in the function guessing the vertex / index counts to prevent that value from being zero, and if it is, refuse to create the tessellation. Attributeless tesselations are always going to require an explicit number of values, and _empty_ tessellations don’t really make sense. I agree with your last point.

**Comment by kpreid** [comment]
I wasn't aware of the attributeless option. To be clear, I intended to discuss `Tess`es which are, by whatever means, no-ops, which don't render anything — not merely attributeless.

Should I take your comment as that I should avoid constructing ones with a zero vertex or index count of any sort, and they might become an error in future versions?

(This doesn't actually remove the possibility of no-ops; one can still do things like passing less than three vertices in triangle mode.)

**Comment by kpreid** [comment]
I'd like to argue a little more for permitting drawing nothing straightforwardly. I just worked on adding some "draw debug boxes" code to my application, and I did it in the `Option<Tess>` style, and it is really quite a lot of boilerplate, at least by lines and indent levels (the `Some(...)` layout is rustfmt's doing):

```rust
let debug_lines_tess = {
    let mut v: Vec<Vertex> = Vec::new();
    // ... compute some vertices from various sources ...
    if v.is_empty() {
        None
    } else {
        Some(
            surface
                .new_tess()
                .set_vertices(v)
                .set_mode(Mode::Line)
                .build()
                .unwrap(),
        )
    }
};

...

if let Some(tess) = debug_lines_tess {
    tess_gate.render(&tess)?;
}
```

Without a nonempty requirement, it would be only:

```rust
let debug_lines_tess = surface
    .new_tess()
    .set_vertices({
        let mut v: Vec<Vertex> = Vec::new();
        // ... compute some vertices from various sources ...
        v
    })
    .set_mode(Mode::Line)
    .build()
    .unwrap();

...

tess_gate.render(&tess)?;
```

Subjectively, permitting empty feels a lot more “high level API” style. Perhaps we could have both benefits by adding an option like `.allow_empty()` on the `TessBuilder`?

**Comment by phaazon** [comment]
I think I see your point, but I’m not a huge fan of creating a GPU resource for nothing. The code you showed with `Some` wrapping is okay to me, especially at render time. On the other side, it would mean to detect when “we shouldn’t create a GPU resource”, and then I need to change all the code / invariants internal to `Tess`. Handling a `Tess` around would mean it can have no GPU representation.

So to answer the initial question, I think it should be considered erroneous and I’ll patch it tonight. Sorry for the delay, btw.
