### ISSUE TITLE
Allow user to specify context attributes when creating the web gl surface

### ISSUE THREAD

**Issue by SnoozeTime** [phaazon/luminance-rs#469]
Currently, the webgl2 context is created with `canvas.getContext("webgl2")`. It would be nice to have an alternative where we can specify the context attributes.
```javascript
gl = canvas.getContext("webgl2", {
  premultipliedAlpha: false  // Ask for non-premultiplied alpha
});
```

In web-sys:
```rust
pub fn get_context_with_context_options(
    &self,
    context_id: &str,
    context_options: &JsValue
) -> Result<Option<Object>, JsValue>
```

The main reason is because of alpha issues: [https://webgl2fundamentals.org/webgl/lessons/webgl-and-alpha.html](https://webgl2fundamentals.org/webgl/lessons/webgl-and-alpha.html)

**Comment by phaazon** [comment]
This is now supported and will be released soon.
