### ISSUE TITLE
How to cull faces?

### ISSUE THREAD

**Issue by twetzel59** [phaazon/luminance-rs#47]
Hello, might it be possible to enable face culling? I am considering writing a game with luminance and face culling is a common and easy optimization.

I looked through the docs and source, but I didn't see any mention of this. A workaround I am using for a test/example introduces GL state and unsafe code, which isn't that preferable...

```rust
entry(|_| {
    pipeline(&screen, [0., 0., 0., 1.], |shade_gate| {
        shade_gate.shade(&shader, |render_gate, _| {
            render_gate.render(None, true, |tess_gate| {
                unsafe { gl::Enable(gl::CULL_FACE); }
                            
                tess_gate.render((&model).into());

                unsafe { gl::Disable(gl::CULL_FACE); }                            
            });
        });
    });
});
```

Thanks!

**Comment by phaazon** [comment]
Yeah, I knew I’d need it and that others would as well. I need to see where to put the concept, maybe in `RenderGate`. I’ll try to add it as soon as possible. Thanks for the report!

**Comment by phaazon** [comment]
I’m going to roll out a new release for you to use face culling (though I need to test it first). Then I’ll release one/several patch versions for enhancing the documentation since… it… just sucks right now!

**Comment by phaazon** [comment]
Tested, working, [released](https://crates.io/crates/luminance/0.24.0).

**Comment by phaazon** [comment]
Feel free to use the `Default` instance in your case. The documentation is not ready but if you need more exotic culling, you’ll find the types straight-forward. :)

**Comment by twetzel59** [comment]
Thanks, this is awesome!
