### ISSUE TITLE
Tess.inst_nb() returns 0

### ISSUE THREAD

**Issue by Lucky4Luuk** [phaazon/luminance-rs#471]
Like the title says, Tess.inst_nb() returns 0.
Backend: `luminance_sdl2`, which relies on `luminance_gl`

In the tessbuilder, I set my vertices, then I set my indices, then I set the rendering mode to Triangle, and that's it.
I can share code, however it's a bit convoluted because I've written a Mesh wrapper to interface with `mlua`, so let me know if it's actually worth sharing the code.

**Comment by phaazon** [comment]
@Lucky4Luuk so you’re not setting the instance number by hand nor passing instance data?

**Comment by phaazon** [comment]
It’s normal that this value is `0` since you don’t have any instances. I think you wanted the number of _indices_, not _instances_.

I’m fixing the docs.
