### ISSUE TITLE
Support changing the size/resolution of an existing `Texture`

### ISSUE THREAD

**Issue by kpreid** [phaazon/luminance-rs#473]
OpenGL/WebGL allows uploading new image data of arbitrary dimensions to an existing texture, but the `luminance` API only allows overwriting texels 1:1 at the originally specified dimensions. 

I propose adding a method on [`Texture`](https://docs.rs/luminance/0.43.2/luminance/texture/struct.Texture.html) which allows specifying a new size along with the data. This will allow updating a texture to a new size/resolution, without needing to structure code responsible for a single texture so that it also has the `GraphicsContext` available (which may be impossible if a pipeline is in progress and the context is therefore borrowed by it).

Use cases I have thought of:

* Resizing a texture atlas to have room for more dynamically created tiles (my use case).
* Streaming asset fetches or expensive procedural generation may upload low-resolution textures before high-resolution ones are available.

**Comment by phaazon** [comment]
> Streaming asset fetches or expensive procedural generation may upload low-resolution textures before high-resolution ones are available.

That’s an interesting need. I think it shouldn’t be too hard to add this kind of feature, indeed.

**Comment by phaazon** [comment]
This is now implemented and will get released soon.
