### ISSUE TITLE
luminance-glfw: let event processing be separate from the graphics context

### ISSUE THREAD

**Issue by kpreid** [phaazon/luminance-rs#475]
In the luminance-examples code, there is the pattern of deferring window resize handling with a flag like:
```rust
    surface.window.glfw.poll_events();
    for (_, event) in glfw::flush_messages(&surface.events_rx) {
      match event {
        WindowEvent::FramebufferSize(..) => {
          resize = true;
        }
        // ...
      }
    }
    if resize {
      back_buffer = surface.back_buffer().unwrap();
      resize = false;
    }
```

While writing my own application using `luminance-glfw`, I found that things like this flag, potentially more elaborate and awkward, must also be added if any events want to borrow `surface` or an object that owns `surface` — for example, if an input event triggers an action that wants to allocate a new `Tess` or `Texture`, then the event or something derived from it must be stored in temporaries to communicate out of the event polling section of the code. It feels somewhat silly to have to do this when there's already a `mpsc::Receiver` involved.

My first idea for how to fix this problem is to make the return value of `GlfwSurface::new` a structure with all fields public (so that the caller can move out of it without losing anything) which contains `window`, `events_rx`, and something implementing `GraphicsContext`. This is almost identical to the current implementation; the difference would be replacing the private field `gl` with a public field of a new type (`GlfwContext`?) that also implements `GraphicsContext`. The `back_buffer()` method would remain where it is; after destructuring it couldn't be used but it's just a convenience anyway.

(Strictly speaking, this would not be necessary since in the current version, I think the caller could `std::mem::swap` out the `events_rx` to take ownership (replacing it with a dummy `Receiver`), but that would be rather ugly.)

Given this change, the application author is free to, for example, move the graphics context to be owned by their rendering subsystem, and keep the `window` and `events_rx` in the main loop, and borrow them separately as needed.

**Comment by phaazon** [comment]
I agree it’s super annoying. I like your idea. It has one drawback, which has to be mentioned: both objects are still connected in a weird way (i.e. destroy the context and the event loop goes brrrrrrrrrr). But I think it’s worth it, and the code change shouldn’t be too complicated.

Thanks for the feedback, I’ll prioritize this.
