### ISSUE TITLE
Add `Tess::index_nb()` consistent with `vert_nb` and `inst_nb`

### ISSUE THREAD

**Issue by kpreid** [phaazon/luminance-rs#478]
`Tess` has `vert_nb()` and `inst_nb()` but no `index_nb()` (or however it would be spelled). Having it would be useful for determining whether to mutate a `Tess` or drop it and create a new one based on the size of the buffers.

**Comment by phaazon** [comment]
Yeah, I think the distinction can be interesting to make. Agreed.

**Comment by phaazon** [comment]
I’m wondering: why did you say that you can use that property to know whether to mutate the `Tess`?

**Comment by kpreid** [comment]
I'm doing “Minecraft-like” chunked voxel rendering, which means that each chunk is a mesh (`Tess`) that may be recomputed and become larger or smaller when game events change its contents. This results in a set of decisions much like resizing a vector:

* If it's equal size in both vertices and indices, then I can just upload new data.
* If it's larger then I have to create a new `Tess`.
* If it's smaller then I can write to a slice and render only those indices, or reallocate smaller to free up GPU memory.

Currently it happens that I have access to a CPU-side copy of the index buffer I uploaded previously, so I can just check its length, but it's a minor bit of clutter in the code.

(For this task it'd also be useful to be able to just ask to resize a `Tess`, but that's an entire new feature and not a case where the API design suggests the function could readily exist.)

**Comment by phaazon** [comment]
Okay, I see the motivation now. Thanks! It’s the next thing in my list.
