### ISSUE TITLE
Tutorial not compiling

### ISSUE THREAD

**Issue by Maan2003** [phaazon/luminance-rs#486]
The [tutorial](https://rust-tutorials.github.io/learn-luminance/chapter_1_2.html) gets different version of glfw. I am using version mentioned on previous page. I have attached [Cargo.lock](https://github.com/phaazon/luminance-rs/files/6000764/Cargo-lock.txt)

`> cargo tree -d`
```
glfw v0.39.1
└── lum-try v0.1.0 (/home/manmeet/src/lum-try)

glfw v0.41.0
└── luminance-glfw v0.14.4
    └── lum-try v0.1.0 (/home/manmeet/src/lum-try)

luminance v0.42.3
└── lum-try v0.1.0 (/home/manmeet/src/lum-try)

luminance v0.43.2
├── luminance-gl v0.16.1
│   └── luminance-glfw v0.14.4 (*)
├── luminance-glfw v0.14.4 (*)
└── luminance-windowing v0.9.3
    ├── lum-try v0.1.0 (/home/manmeet/src/lum-try)
    └── luminance-glfw v0.14.4 (*)
```

**Comment by NecroTechno** [comment]
I was able to resolve this by changing the explicit glfw dependency in my Cargo.toml to v0.41

```toml
[dependencies]
luminance = "0.42"
luminance-glfw = "0.14"
luminance-windowing = "0.9"
glfw = "0.41"
```

it does still need to be resolved in the book, though.

**Comment by phaazon** [comment]
Yes, the [current version is not up to date](https://rust-tutorials.github.io/learn-luminance/crate-setup.html). I need to update it.

**Comment by phaazon** [comment]
This is now fixed.
