### ISSUE TITLE
Luminance is Awesome! 🚀

### ISSUE THREAD

**Issue by zicklag** [phaazon/luminance-rs#488]
Hi there, just wanted to shout out and day that Luminance is really great. I've just gotten into it and it is _so_ nice after trying to use OpenGL to do the same things. I finally have a decent grasp on OpenGL, but understanding it is one thing and _using_ it is another. It's API is infinitely error prone. I was thinkining I'd have to make my own abstraction layer just to make it possible to write a small sprite renderer in, but then I remembered luminance!

Loving it so far, thanks!

**Comment by phaazon** [comment]
Hey, thanks for the kind words! I’m glad people like it. :slightly_smiling_face:
