### ISSUE TITLE
Dual Web/Desktop Example Project

### ISSUE THREAD

**Issue by zicklag** [phaazon/luminance-rs#490]
I found it extremely useful how the `egui` project had a template repo that was setup to support both web and desktop from the same codebase and I thought that it would be great to have for Luminance. I've already created a repo just for my own testing that works: https://github.com/zicklag/me-learning-luminance.

It needs lots of cleanup so I wouldn't use that exactly, but I was curious if there is a place we would want to put it or something if I got the chance to open a PR and whether or not this is something you would want.

**Comment by phaazon** [comment]
Hello,

The [hello-world](https://github.com/phaazon/luminance-rs/blob/master/luminance-examples/src/hello-world.rs) and [hello-world-web](https://github.com/phaazon/luminance-rs/blob/master/luminance-examples-web/src/lib.rs) are similar to what you’re mentioning, no?

**Comment by zicklag** [comment]
Similar, but what I mean is having one repo that user's can just clone or folder they can just copy that will be already setup for compiling to web and desktop using the same codebase.

The hello world and hello world web are separate examples so while they show you how to do one or the other they don't have the platform `#[cfg]` checks make it work for both.

I'm imagining being able to just fill in your `init` renderer and `update` renderer code and having scripts or a [`justfile`](https://github.com/casey/just) ( maybe to opinionated ) to build for both web and desktop so user's can get started real quickly.

**Comment by phaazon** [comment]
This is now implemented.
