### ISSUE TITLE
What Should I Call my Luminance Platform Crate?

### ISSUE THREAD

**Issue by zicklag** [phaazon/luminance-rs#491]
I need to create a Luminance surface from a winit window that I don't have control over the creation of. To do that I was going to use `surfman` for the context creation. What whould I call the crate in this case? I assume I don't call it `luminance-surfman` because that would make it seem official?

Should I call it `luminance-contrib-surfman` or `contrib-luminance-surfman` or something like that?

PS: Man that was easy! It's already working. It took me just an hour! https://github.com/katharostech/luminance-surfman.

**Comment by phaazon** [comment]
I’m glad to see you were able to make it work first shot! I don’t know `surfman` though, I need to investigate a bit.

**Comment by zicklag** [comment]
I've got another crate now that I haven't published to crates.io: `luminance-glow`. It's a backend for Luminance built on [`glow`](https://docs.rs/glow) which can target WebGL 1, WebGL 2, and OpenGL.

Are you OK if I publish the crates under the names `luminance-surfman` and `luminance-glow`, or should I namespace them somehow so that they don't start with `luminance-`?

**Comment by phaazon** [comment]
Oh sure you can, feel free to!
