### ISSUE TITLE
Is There a Way to Query the Maximum Number of Textures in an Array Texture?

### ISSUE THREAD

**Issue by zicklag** [phaazon/luminance-rs#492]
I'm planning on using an Array Texture to store a collection of textures that I can use in one render pass to render a bunch of sprites, but I need to be able to query the maximum number of textures that I am allowed to stick into one texture array. Is there a way to do that?

**Comment by phaazon** [comment]
That’s a good question and so far I don’t think so. I plan to add an API for querying limits but it’s not started yet.

**Comment by zicklag** [comment]
OK, cool. I don't need it immediately or anything, and if necessary I can always do some workaround by accessing the raw GL context to make the query if I need to. Thanks. :slightly_smiling_face:

**Comment by phaazon** [comment]
This is now implemented and will be released soon.

**Comment by zicklag** [comment]
Awesome! :tada:
