### ISSUE TITLE
Feature: custom mipmap uploads

### ISSUE THREAD

**Issue by kpreid** [phaazon/luminance-rs#504]
Currently, the only way to have mipmaps is to specify `GenMipmaps::Yes` and have them computed. I propose adding the ability to upload texels for multiple mipmap levels.

This would be useful, for example, for any application using texture atlases, to generate mipmaps that do not bleed between regions of the atlas. Custom mipmaps can also contain better resampling or special effects. For my own application, I'm not in a rush to use this feature, but I will when it's available, and it seems like a good (or slightly late) time to ask since there's some API revision going on.

**Comment by phaazon** [comment]
I’m not sure mipmaps should be used like that? To me, mipmaps are just an optimization for anisotropic filtering. People should rather use texture arrays (layers) for that, no?

**Comment by kpreid** [comment]
If by 'use arrays for that' you mean 'use arrays for atlases', then array textures have several limitations: they have a maximum number of layers that isn't very large for some purposes, require every layer to be the same size, and there's no `Dim3Array`.

If you mean using arrays in place of custom mipmap levels: all the layers have to be the same size, so many texels would be wasted unless an elaborate remapping scheme was used. And, relevant to my plans in particular, there's no `Dim3Array`.

**Comment by phaazon** [comment]
That makes sense. Adding an API for that is not hard at all and I should have some time to add it to the current batch of things to do. Thanks for reporting!

**Comment by phaazon** [comment]
I think we can close this now that mipmaps can be [uploaded manually](https://docs.rs/luminance/0.47.0/luminance/texture/enum.TexelUpload.html).
