### ISSUE TITLE
MacOS Compatible Graphics Backend

### ISSUE THREAD

**Issue by zicklag** [phaazon/luminance-rs#510]
Currently Luminance doesn't run on MacOS ( at least according to my test ) probably due to the deprecation of OpenGL. I currently plan on using the WebGL 1 backend and [Tauri](https://tauri.studio) to target Mac, but that's not ideal.

It seems like we have a few options for targeting MacOS natively:

- Create a metal Backend for Luminance
- Create a gfx backend for Luminance
- Create a WGPU backend for Luminance

I feel like WGPU would probably be the best option, because it's got a safe API which would be nice.

There's a very slight chance I might find time to look into this.

**Comment by phaazon** [comment]
Well, yeah, a metal backend would be nice, but I don’t plan on writing it soon. Apple is doing the wrong thing here, deprecating OpenGL and not supporting Vulkan directly. A Vulkan backend is planned, landing I have no idea when, but it’s still a bigger priority than macOS. Probably worth a shot looking at MoltenVK.

Do not lose your time making a `gfx` backend though. I won’t accept it as part of luminance.

**Comment by robert-chiniquy** [comment]
Just wanted to comment that, right now at least, Luminance runs fine on my Mac on Big Sur using `OpenGL.framework` (which I think is a compat layer over Metal).
