### ISSUE TITLE
WebGL: Texture properties seem to be getting lost on the way to the browser

### ISSUE THREAD

**Issue by robert-chiniquy** [phaazon/luminance-rs#514]
Hi! This question comes out of this comment: https://github.com/emilk/egui/discussions/443#discussioncomment-837647

I believe I am doing what is needed to set the following texture properties:
```
textureType: UNSIGNED_BYTE
format: RGBA
internalFormat: SRGB8_ALPHA8_EXT
```

In this repo: https://github.com/robert-chiniquy/egui-luminance

Specifically at these 2 points:
* https://github.com/robert-chiniquy/egui-luminance/blob/main/src/egui_luminance.rs#L96
* https://github.com/robert-chiniquy/egui-luminance/blob/main/src/egui_luminance.rs#L255

But the code is failing in a way that suggests an issue with the texture/sampler, and inspecting browser state with Spector.js I found that those properties do not seem to be present in the texture.

I traced the flow of the texture methods I am calling through Luminance, and it definitely looks to me as though they should be there, but I think they aren't (based also on the way the render is failing). I may be misunderstanding Spector's output, or I suppose I could have missed something obvious about textures in Luminance? 

Any help would be hugely appreciated.

**Comment by phaazon** [comment]
Hello!

Yes, you are setting them correctly. I don’t know what `Spector.js` does (how does it _inspect_ the properties of textures). [The code that does that on the luminance side](https://github.com/phaazon/luminance-rs/blob/master/luminance-webgl/src/webgl2/pixel.rs#L283-L289):

```rust
    (Format::SRGBA(Size::Eight, Size::Eight, Size::Eight, Size::Eight), Type::NormUnsigned) => {
      Some((
        WebGl2RenderingContext::RGBA,
        WebGl2RenderingContext::SRGB8_ALPHA8,
        WebGl2RenderingContext::UNSIGNED_BYTE,
      ))
    }
```

You’re using the `SRGBA8UI` pixel type, defined [here](https://github.com/phaazon/luminance-rs/blob/master/luminance/src/pixel.rs#L990-L996), which seems all good. However, it’s not using the `_EXT` extension but the WebGL2 spec type.

Now that I think about it… if you are using WebGL1, then the current backend (WebGL2) doesn’t support it yet.

**Comment by robert-chiniquy** [comment]
Hi! Thanks for the response!

I'm definitely using WebGL2. I assume `Spector.js` is just using the WebGL APIs which let you query state off the context.

Since I am using WebGL2, not using the `_EXT` type is correct, right? 

I need to dig back into this, this issue stumped me for a while so I went to work on other things. I really appreciate the design of the Luminance API and the quality of the code. I would love to be able to use Egui within it.

**Comment by robert-chiniquy** [comment]
OK! Narrowed this down more.

My working Egui example (not using Luminance) shows this memory used for textures (viewing this with Spector.js again): 524288. This is `2048 * 64 * 4`, and the dimensions of the texture are 2048x64, and the pixels are RGBA, so this number is perfect.

My attempt at Egui under Luminance shows 0 bytes used for textures, which explains why I saw (in this comment: https://github.com/emilk/egui/discussions/443#discussioncomment-837647) that the texture had no `width` or `height` set.

I am trying to upload the texture in this line: https://github.com/robert-chiniquy/egui-luminance/blob/main/src/egui_luminance.rs#L156

I am binding the texture here: https://github.com/robert-chiniquy/egui-luminance/blob/main/src/egui_luminance.rs#L307

I really think there must be something wrong with how I am uploading the texture, seeing that Spector.js is reporting 0 bytes, and the texture pixels all come through as white from the sampler in the shader. 

Does anything stand out in the above code which could stop the texture from being uploaded at all?

**Comment by robert-chiniquy** [comment]
I've verified that the texture is making it to the browser. Looks like you were right to doubt that data from Spector.js btw, it is weird that those differences exist but they clearly don't mean what I thought they did. Made a little progress solving my issue, not there yet, but I'm sure this isn't an issue with Luminance. Thanks for taking a look at it! I really appreciate your work.
