### ISSUE TITLE
Multiple color slots in framebuffer?

### ISSUE THREAD

**Issue by TheJebForge** [phaazon/luminance-rs#526]
I'm trying to figure out how to do deferred rendering, I want to do a single shader for a mesh that would generate 4 color buffers for various things. I noticed there is a way to have multiple color attachments with frame buffer in documentation, but it's really not clear without an example on how to make a framebuffer with many color attachments

**Comment by phaazon** [comment]
You can find [an example here](https://github.com/phaazon/luminance-rs/blob/master/examples/common/src/mrt.rs). Thanks for reaching out, I will try to enhance the documentation about that!

**Comment by phaazon** [comment]
Basically, the idea is that you can use any type implementing `ColorSlot`, but you probably don’t want to create such a type by yourself. Tuples already work up to 16 elements, so you can use pixel formats in tuples to create as many color attachments as you want. This doesn’t work, obvously, for the depth buffer (you can have only one pixel format for `DepthSlot` for now, and you are very limited in the list of pixel formats there).
