### ISSUE TITLE
Links under "Other crates" in README are broken

### ISSUE THREAD

**Issue by themaxdavitt** [phaazon/luminance-rs#527]
The links to ["luminance-examples"](https://github.com/phaazon/luminance-rs/blob/master/luminance-examples) and ["luminance-examples-web"](https://github.com/phaazon/luminance-rs/blob/master/luminance-examples-web) in the ["Other crates" section of the README](https://github.com/phaazon/luminance-rs#other-crates) are broken.

**Comment by phaazon** [comment]
Oh yeah, it’s due to a big refactoring I did in the past months. Thanks for noticing!
