### ISSUE TITLE
render arbitrary slice of a Tess

### ISSUE THREAD

**Issue by tinaun** [phaazon/luminance-rs#54]
`one_sub()` only seems to render the first n verts.

i want to render half of my buffer, change some uniforms, and then render the other half. is there a idiomatic way to do this?

**Comment by phaazon** [comment]
Hi! Thanks for reaching out.

Not yet, however, I can add the feature if you think it’d be cool. It shouldn’t be that hard to implement. :)

**Comment by tinaun** [comment]
yeah! ive gotten around it atm by just making more buffers, but i think i could do a pr if you want, too.

**Comment by phaazon** [comment]
As you wish. I can work on it on this weekend, too.

**Comment by phaazon** [comment]
I’m on it.

**Comment by phaazon** [comment]
I’m getting back to you. See [this](https://github.com/phaazon/luminance-samples-rs/tree/master/samples/one_slice) for example on how to use the feature you’re looking for. ;)
