### ISSUE TITLE
black textures

### ISSUE THREAD

**Issue by tinaun** [phaazon/luminance-rs#55]
i created a very simple debug texture (32x32 Flat Dim2 RGBA8UI, no mipmaps), and i can read and write from it fine, but it always shows up black when i try to use it in my shader. other uniforms work just fine, and my uv coords are being passed to my fragment shader correctly.

uniforms:
```
pub struct SUniforms<'a: 'b, 'b> {
    pub view: Uniform<[u32; 2]>,
    pub tex: Uniform<&'b BoundTexture<'a, Texture<texture::Flat, texture::Dim2, pixel::RGBA8UI>>>,
}
```

render loop:
```rust
    window.draw(|| {
        entry(| gpu | { 
            pipe(&fb, [1.0, 0.0, 0.0, 1.0], |shader_gate| {
                shader_gate.shade(&program, |render, uniforms| {
                    // update uniforms
                    let tex = gpu.bind_texture(&tex);
                    uniforms.view.update(size);
                    uniforms.tex.update(&tex);    

                    // draw
                    render.render(alpha, |tess_gate| {
                        tess_gate.render((&tess).into());
                    })
                });
            });
        });
    });
```
[renderdoc output](https://drive.google.com/file/d/1UesGjRa0mkS64YbMpZQBZUmPHPB88HDx/view)

**Comment by phaazon** [comment]
I don’t have `renderdoc` right now. I’ll have a look when I get home. What sampler are you using in your shader?

**Comment by tinaun** [comment]
```Sampler {
    wrap_r: texture::Wrap::Repeat, 
    wrap_s: texture::Wrap::Repeat,
    wrap_t: texture::Wrap::Repeat,
    min_filter: texture::MinFilter::Linear,
    mag_filter: texture::MagFilter::Linear,
    depth_comparison: None,
};```
```
in vec2 fPos;

out vec4 color;

uniform sampler2D tex;

void main() {

    color = vec4(texture(tex, fPos).rgb, 1.0);
    //color = vec4(1.0, 1.0, 1.0, clamp(fPos.x + fPos.y, 0.0, 1.0));
}```

**Comment by phaazon** [comment]
Try with `uniform usampler2D`, because your texture has an internal format of `RGBA8UI`.

On a more general note, I need to patch the check code for this. Most uniforms would have yielded a type mismatch (you can try it out), but with arrays and textures, I just assume it’s always ok for now.

**Comment by tinaun** [comment]
yep, that was it! thanks a bunch. i checked for all uniform warnings, so i didn't think my uniform types could have been off after i didn't get any more warnings! good to know

**Comment by phaazon** [comment]
Yeah, it’s on me. I’ll patch that soon. I won’t close your issue so that I can use it as backlog, if you don’t mind. The patch is not hard to write, it just requires a bit of refactoring, nothing hard. I’ll do that on this weekend if I find enough spare time.

Thanks again for reaching out!

**Comment by phaazon** [comment]
OK, I’ll work on that right now.

**Comment by phaazon** [comment]
@tinaun I’ll release a new version of luminance soon but if you want to test with the current `HEAD`, you might give it a try! Just use the initial code you posted. You should now have a type mismatch.

**Comment by tinaun** [comment]
awesome!

**Comment by phaazon** [comment]
[luminance-0.28](https://crates.io/crates/luminance/0.28.0) ships with it! :)
