### ISSUE TITLE
What's the replacement for new_texture_no_texels?

### ISSUE THREAD

**Issue by kpreid** [phaazon/luminance-rs#569]
luminance 0.45 deleted `new_texture_no_texels()`. As the changelog says:

> Change the way texture uploads / texture creation works. Methods such as `GraphicsContext::new_texture_no_texels` are removed. Instead, all the texture API functions must go through the new `TexelUpload` type, which encodes various different situations:

But how do I express “I don't want to upload any texels now” with `TexelUpload`? All possible inputs seem to result in a `NotEnoughPixels` error if they don't have all the texels.

(This is phrased as a question but it might be an API bug or a documentation bug.)

**Comment by ColonelThirtyTwo** [comment]
Yeah, seems like an oversight in the new API. It should be easy to add another option to `TexelUpload`.

**Comment by phaazon** [comment]
```rust
TexelUpload::base_level_with_mipmaps(&[], mipmaps),
```

Is what is currently being used. A missing bit of documentation, I guess.

**Comment by kpreid** [comment]
That doesn't seem to work. For example, if I modify my code to

```rust
        let texture = context.new_texture(
            layout.dimensions(),  // [256, 256, 256]
            Sampler {
                wrap_s: Wrap::ClampToEdge,
                wrap_t: Wrap::ClampToEdge,
                wrap_r: Wrap::ClampToEdge,
                mag_filter: MagFilter::Nearest,
                min_filter: MinFilter::Nearest,
                ..Sampler::default()
            },
            TexelUpload::base_level_with_mipmaps(&[], 0),
        )?;
```

then I get the runtime error `NotEnoughPixels { expected_bytes: 67108864, provided_bytes: 0 }`.

Ah, I see a possible misunderstanding. I want to create a texture _of a specific nonzero size_ so that I can later write to parts of it (in texture atlas fashion) using `upload_part()`. Uploading 64 MiB of dummy pixels can take around 100 ms on the WebGL backend in Chrome, and I'd like to avoid a frame hiccup that large in the event I need to resize the atlas.

**Comment by phaazon** [comment]
Yep, I reproduce with `mrt` example. Thanks for noticing.

**Comment by kpreid** [comment]
`TexelUpload::reserve` in luminance 0.46 is working for what I needed.
