### ISSUE TITLE
Intermixing of Tess's with different structures

### ISSUE THREAD

**Issue by ColonelThirtyTwo** [phaazon/luminance-rs#574]
Working on rendering models from GLTF files with luminance.

The GLTF format can specify different index types for different models - one model might use `u8` indices, another might use `u32`, and yet another might not need indices. However, because the `Tess` structure has the index type as a type parameter, you cannot store `Tess`s with different index buffer types in the same collection, as they have different types. Ideally, there should be a super-type of some sort to allow storing `Tess`s with different index buffer types in the same collection, even if they don't allow reading and mutating the vertex or index data anymore and only allow rendering.

This also applies for whether the buffers are interleaved. It also applies to the vertex semantics, but I think it makes sense to keep `Tess`s with different vertex semantics separate, given that they require different shader setups.

One possible solution is to have a trait, lets call it `RenderTess<V>`, implemented for all `Tess`, is `?Sized`, and is accepted by `TessGate::render`.

Workaround - you can create an enum with one entry per possible `Tess` variation, but that's annoying to have to do and has combinatorial explosion.

**Comment by phaazon** [comment]
Yes, `Tess` is indexed at compile-time, and this is a feature that is pretty important. It allows a wide variety of invariant checks and type soundness. 

> Workaround - you can create an enum with one entry per possible Tess variation, but that's annoying to have to do and has combinatorial explosion.

You have your solution already. :slightly_smiling_face: On a general basis, when you want something _dynamic-ish_ like what you just described, an `enum` is what you want, or a trait object but I don’t think you would benefit from that.
