### ISSUE TITLE
Cannot get basic triangle drawn

### ISSUE THREAD

**Issue by osmarks** [phaazon/luminance-rs#60]
I've attempted to get a simple triangle drawn, using the example provided ([this one](http://phaazon.blogspot.co.uk/2017/09/state-of-luminance.html)). The example seems to be slightly outdated, so I modified it slightly - the code for this can be found [here](https://github.com/osmarks/3d-test). It doesn't work for me (black screen), and neither does the example there.

**Comment by phaazon** [comment]
Hello,

Yeah, I need to update the examples. I’m having a look at your example. Thanks for reaching out.

**Comment by phaazon** [comment]
Ok, so the problem comes in because of two configurations:

```
const TRIANGLE_VERTS: [Vertex; 3] = [
    ([-0.5, -0.5], [0.8, 0.5, 0.5]), // red bottom leftmost
    ([-0., 0.5], [0.5, 0.8, 0.5]), // green top
    ([0.5, -0.5], [0.5, 0.5, 0.8]) // blue bottom rightmost
];
```

This geometry is defined via CW spelling.

```
 let rdr_state = RenderState::default();
```

This enables CCW culling. So, what it means is that your triangle won’t show up because it’ll get culled (it’s facing backwards). You can fix that by either disabling culling:

```
    let rdr_state = RenderState::default().set_face_culling(None);
```

… or by telling to cull on CW direction:

```
    let rdr_state = RenderState::default().set_face_culling(FaceCulling::new(FaceCullingOrder::CW, FaceCullingMode::Back));
```

Or by leaving it the way it is but specifying your geometry in CCW direction:

```
    let rdr_state = RenderState::default().set_face_culling(FaceCulling::new(FaceCullingOrder::CW, FaceCullingMode::Back));
```

**Comment by phaazon** [comment]
On a more general note, what do you think should be the best here as default? CCW is very common among 3D tools (Blender, Maya, ZBrush, 3DS Max, etc.), but it can get confusing if you define your geometry in CW as you did – you might think of a bug while it’s not, it’s just a default configuration.

> Note: I don’t like defaults, even though they are handy. I might set the default to *no culling*… should I?

**Comment by osmarks** [comment]
I don't really have much of a preference on culling order.
The triangle is displayed now, though, thanks.

**Comment by phaazon** [comment]
Happy you work it out. Thanks again for reaching out. I shall close this issue then.
