### ISSUE TITLE
Difference of behavior of the program between Framebuffer::default(..) and Frambuffer::new(..)

### ISSUE THREAD

**Issue by rgiot** [phaazon/luminance-rs#65]
Hello,
I may have missed something when digging in the code and documentation, but I'm unable to manually build the framebuffer to display something in the glw window.

If I create the framebuffer using:
```rust
let framebuffer = Framebuffer::default(size); 
```
the drawing corresponds to what I want.

But, if I create the framebuffer using:
```rust
let framebuffer : Framebuffer<Flat, Dim2, Texture<_, _, RGBA32F>, ()>= Framebuffer::new(
            &mut dev,
            size,
            0
        ).expect("Unable to create the framebuffer");
```

or even in order to be more close to the type provided by default
```rust
let framebuffer : Framebuffer<Flat, Dim2, (), ()>= Framebuffer::new(
            &mut dev,
            size,
            0
        ).expect("Unable to create the framebuffer");
```

the program blindly fails: there is no panic but the glfw stays black.

No idea if I'm wrong somewhere or if there is an issue in the Framebuffer builder

edit: if it has an impact, output of the fragment shader is a `vec4`

**Comment by phaazon** [comment]
Hello.

Do you have a minimal reproductible example? Also, which version of `luminance`?

**Comment by rgiot** [comment]
Yep, I've been able to reproduce it.
First assume you have the sample version that compiles with latest luminance version (and that works properly): https://github.com/phaazon/luminance-samples-rs/pull/1/files

If you apply the following patch:
```diff
diff --git a/samples/one_slice/src/main.rs b/samples/one_slice/src/main.rs
index da20290..3c7c13c 100644
--- a/samples/one_slice/src/main.rs
+++ b/samples/one_slice/src/main.rs
@@ -14,7 +14,9 @@ use luminance::tess::{Mode, Tess, TessRender};
 use luminance::render_state::RenderState;
 use luminance_glfw::surface::*;

- use luminance::context::GraphicsContext;
+use luminance::context::GraphicsContext;
+use luminance::texture::{Dim2, Flat};
+

 #[derive(Copy, Clone, Debug)]
 enum Demo {
@@ -61,8 +63,14 @@ fn main() {
     }

     let size = dev.size();
+    let framebuffer : Framebuffer<Flat, Dim2, () /*Texture<_, _, RGBA32F>*/, ()>= Framebuffer::new(
+        &mut dev,
+        size,
+        0
+        ).expect("Unable to create the framebuffer");
+
        dev.pipeline_builder().pipeline(
-          &Framebuffer::default(size), [0., 0., 0., 0.], |_pipeline, shd_gate| {
+          &framebuffer, [0., 0., 0., 0.], |_pipeline, shd_gate| {
         shd_gate.shade(&program, |rdr_gate, _| {
           rdr_gate.render(RenderState::default(), |tess_gate| {
             match demo {
```

that only replace the default Framebuffer by a manually created one, the bug appears: the window stays empty.

**Comment by phaazon** [comment]
Oh, `luminance-samples-rs` hasn’t been updated for a while… I really, really need to update it. Thanks for reporting! I’ll have a look as quick as possible!

**Comment by phaazon** [comment]
What do you do with that framebuffer? And what do you expect to see?

**Comment by rgiot** [comment]
in this case I expect to see the two triangles of the demo program; instead there is nothing. Also, if I change the background color to not be black, the window is still back

**Comment by phaazon** [comment]
Oh you scared me! Ok, this is a perfectly normal behavior. What the code you pasted does is to perform the render of your triangles in an _offscreen_ framebuffer. Once the pipeline has finished, the framebuffer contains the triangle. You can verify this by running the application in either `apitrace` or `renderdoc`.

Maybe I should change the name of the `Framebuffer::default` method so that it’s more obvious what it does. It’s a `Framebuffer` bound to the current _back buffer_. When you render to it, you fill the backbuffer. Swapping the framebuffer chain will then swap that framebuffer with the the front one (i.e. the one on your screen!).

**Comment by rgiot** [comment]
The swapping is needed even with the `FrameBuffer::default` (see line 88 https://github.com/phaazon/luminance-samples-rs/pull/1/files#diff-8ff38154dd5ff534298cf99a392f7ec1R82).
So I use it even for this manually created framebuffer.

So what do I need to call (in addition to  `dev.swap_buffers();` to display its content ?

**Comment by phaazon** [comment]
You need another pass to render to the default framebuffer and a special shader to copy from the first framebuffer.

**Comment by rgiot** [comment]
Ok, so manually creating this stuff is maybe not what I wanted to do.

**Comment by phaazon** [comment]
If you only want to draw to the string and don’t have any specific requirement for special effects, yeah, you should be good to go with the `Framebuffer::default` method. I shall modify its name and add more documentation so that it’s less confusing. Thanks again for reporting! I’ll leave the issue open ’till I fix the doc, at least.

**Comment by rgiot** [comment]
With the documentation change of the related pul lrequest, I may not have done this mistake.
(The example  7 also helps well to understand how to use buffers)

**Comment by phaazon** [comment]
Great then. :)
