### ISSUE TITLE
Uniform detection behavior is different with/without using the geometry shader

### ISSUE THREAD

**Issue by rgiot** [phaazon/luminance-rs#68]
Hello,

I'm trying to use uniforms (some transformation matrices) on a program using the geometry shader.
It is the vertex shader that retreives the uniforms.
The creation of the program systematically fails by trowing such kind of error message: `UniformWarning(Inactive("proj"))`.
However when I build a program with exactly the same vertex and fragment shaders, but without the geometry shader, the program is created without any problem.

Is this behavior normal ? or is this a bug ?

**Comment by phaazon** [comment]
Please provide the three shader stage codes. :)

**Comment by rgiot** [comment]
Here are the simplified shaders

# Fragment
```glsl
in vec4 g_Color;
out vec4 FragColor;
void main() {
    FragColor = g_Color;
}
```

# Geometry
```glsl
 layout(points) in;
 layout(triangle_strip, max_vertices=6) out;
in vec4 v_pos[];
in vec4 v_color[];
out vec4 g_Color; 	// Inner color
 void main() {
	 gl_Position = v_pos[0]; 
	 g_Color = v_color[0];
	 EmitVertex();
 }
```

# Vertex
```glsl
layout (location = 0) in vec3 a_pos;
layout (location = 1) in vec2 a_size;
layout (location = 2) in vec4 a_color;
layout (location = 3) in uint a_shape;
out vec4 v_pos;
out vec4 v_color;
uniform mat4 proj;
uniform mat4 view;
uniform mat4 model;
void main() {
  gl_Position = proj * view * model * vec4(a_pos, 1);
  v_pos = vec4(a_pos, 1);
  v_color = a_color;
}
```


So in any cases gl_Position of the vertex shader contains something computed by the uniforms.

However, it is true that the gl_Position of the geometry shader do not use the one of the vertex shader (I forget to make the transformation also there). To use `gl_Position = gl_in[0].gl_Position;` do not raise the issue.

Anyway, is it the correct behavior for luminance to raise such error ? The uniform is used; but not the result of its use

**Comment by phaazon** [comment]
I’ll try to test it, but the geometry shader is wrong. You’re not emitting a sufficient amount of vertices for `triangle_strip`.

**Comment by phaazon** [comment]
Also, if you have a geometry shader, writing to `gl_Position` in the vertex shader is useless if you don’t use `gl_In[x].gl_Position` in the geometry shader.

**Comment by rgiot** [comment]
In my real code I issue the 6 vertices.

**Comment by rgiot** [comment]
And of course, if I move the uniforms from the vertex shader to the geometry shader and really use it there, the issue is not raised

**Comment by phaazon** [comment]
Ok, this is not a bug. The OpenGL driver just understood that `proj`, `view` and `model` are not used in your example. Adding a *geometry shader* in beetwen a vertex shader and a fragment shader changes the semantics of the `gl_Position` variable in the vertex shader a little bit. This value is now **passed to the geometry shader**, so, as I said, if you don’t use it, the GLSL compiler will discard any code path leading to it. You want `gl_in[x].gl_Position`.
