### ISSUE TITLE
Matching shader uniform types with texture types.

### ISSUE THREAD

**Issue by saolsen** [phaazon/luminance-rs#87]
Is there a good way to see what the mappings from uniform interface to glsl uniform types is? I have an array of rgba pixels I captured from the screen and am trying to upload to a texture and display. My interface is
```
uniform_interface! {
    struct ShaderInterface {
        tex: &'static BoundTexture<'static, Flat, Dim2, RGBA8UI>
    }
}
```
I upload the array with upload_raw and then in my shader trying to sample it with uniform sampler2D tex; but getting an error program created: `UniformWarning(TypeMismatch("tex", "requested usampler2D doesn’t match"))`

**Comment by phaazon** [comment]
Yep, a texture with format `RGBA8UI` uses a unsigned 8-bit texture sized format. You have to use, as the error states, the `usampler2D` type in your shader. :)
