### ISSUE TITLE
Re-introduce backends

### ISSUE THREAD

**Issue by phaazon** [phaazon/luminance-rs#95]
Backends are needed if we want to enable compiling to WASM, since WASM doesn’t support the native OpenGL libraries (it relies on WebGL, so we’ll have to change the bindings).

This is also going to change the `metagl` module (used for the `std` feature gate). Finally, as I want to move to / support Vulkan, this is an important change that must be prioritized.

**Comment by phaazon** [comment]
I’m removing this from `luminance-1.0` as it’s been months I tried to have spare time to work on that, and fuck it, I have a life too. That feature is clearly doable but all those traits I have everywhere makes `luminance` gets away from its initial scope: being a simple library.

If I ever introduce backends into `luminance`, it’s likely to be in the form of feature-gates. I know, it’s not the best, but it will be easier to maintain.

**Comment by icefoxen** [comment]
Have you considered the [glow](https://crates.io/crates/glow) crate?  Seems like it's designed for this sort of use case, and you wouldn't need multiple backends.

**Comment by phaazon** [comment]
I just had a look at it, I need to think about it. Especially, it’s feature-gated, I’m not sure how to feel about that.
