### ISSUE TITLE
Proc-macro: UniformInterface

### ISSUE THREAD

**Issue by phaazon** [phaazon/luminance-rs#99]
We want a procedural macro that does the job of the current [`macro_rules! uniform_interface`](https://docs.rs/luminance/0.30.1/luminance/macro.uniform_interface.html)

**Comment by tinaun** [comment]
i have a proc macro for this in my project that uses luminance, i need to update it for the latest version of rust and luminance but its there if you want it

**Comment by phaazon** [comment]
Sure! What project are you using?
